org.gradle.jvmargs=-Xmx3G -Dnet.minecraftforge.gradle.check.certs=false
org.gradle.daemon=false

minecraft_version=1.20.1
minecraft_version_range=[1.20.1,1.21)
forge_version=47.1.3
forge_version_range=[47,)
loader_version_range=[47,)
mapping_channel=official
mapping_version=1.20.1

mod_id=recipe_linkage
mod_name=Recipe Linkage
mod_display_name=Recipe Linkage
mod_license=MIT License
mod_version=0.0.2
mod_group_id=com.amicbeam.recipelinkage
mod_authors=AmicBeam
mod_description=Data-driven recipe research table for material-linkage puzzles and AStages progression.

jei_file_id=7361881
